<a href="https://colab.research.google.com/github/kirthickranjan/ML_Projects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np


1D Array


In [ ]:
a=np.array([1,4,3,7,1,7,8,5])
print(a)

[1 4 3 7 1 7 8 5]


2D Array

In [ ]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


Arange Function

In [ ]:
sequence_of_integers=np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [ ]:
x=np.array([1,2])
y=np.array([1.2,3.4])

ones(a,b)-generate one
zeros(a,b)-generate zeros
random.random(a,b)-generate random numbers

a-ranges b-size

In [ ]:
z=np.zeros((4,2))
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
c=np.ones((5,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
x=np.random.random((4,4))
print(x)

[[0.40012338 0.32045913 0.94547992 0.5681179 ]
 [0.33427781 0.36698793 0.07045703 0.64663104]
 [0.13691753 0.75032922 0.5889439  0.63172443]
 [0.09828659 0.90900123 0.21952416 0.31630657]]


Also pass incremens in arange function

In [ ]:
a=np.arange(5,20,3)
print(a)

[ 5  8 11 14 17]


Line spacing- gives equal and split numbers

In [ ]:
g=np.linspace(0,1,num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


Indexing

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(a[3])
print(a[0:5])
print(a[0:6:2])

4
[1 2 3 4 5]
[1 3 5]


In [ ]:
b=np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(b[0,1])
print(b[1:3])
print(b[0:2,0])

2
[[3 4]
 [5 6]]
[1 3]


In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(b[1,:])

[5 6 7 8]


In [ ]:
print(b[1:2,:])

[[5 6 7 8]]


In [ ]:
print(b[[1],:])

[[5 6 7 8]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
a.shape

(4, 3)

In [ ]:
b=np.array([0,2,0,1])
print(a[np.arange(4),b])

[ 1  6  7 11]


In [ ]:
a[np.arange(4),b]+=10
print(a)

[[41  2  3]
 [ 4  5 46]
 [47  8  9]
 [10 51 12]]


In [ ]:
a=np.array([1,8,9,-3,2,4,7,9])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>1)[0])
print(np.where(a>=a[np.argmax(a)])[0])

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 4 5 6 7]
[2 7]


Adding removing elements

In [ ]:
#add
a=[0]
a=np.append(a,[1,2,3,4])
print(a)

[0 1 2 3 4]


In [ ]:
#Delete
a=np.delete(a,[2,3])
print(a)

[0 1 4]


In [ ]:
%%time
x=np.sum(a)

CPU times: user 100 µs, sys: 0 ns, total: 100 µs
Wall time: 106 µs


In [ ]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162]]


Matrix Multiplication

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[3]])
print(x.dot(y))
print(np.dot(x,y))
print(x@y)

[list([5, 6, 3, 3]) list([5, 6, 5, 6, 5, 6, 3, 3, 3, 3])]
[list([5, 6, 3, 3]) list([5, 6, 5, 6, 5, 6, 3, 3, 3, 3])]
[list([5, 6, 3, 3]) list([5, 6, 5, 6, 5, 6, 3, 3, 3, 3])]


<ipython-input-43-6af4dc040242>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y=np.array([[5,6],[3]])


In [ ]:
print(np.max(x))
print(np.min(x))
print(np.sum(x))

4
1
10


In [ ]:
w=np.array([[1],[2],[3]])
print(w)
w.shape


[[1]
 [2]
 [3]]
[1 2 3]


In [ ]:
z=w.squeeze()
print(z)
z.shape

[1 2 3]


(3,)